[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  # For your static JSON files
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400" # Cache for 1 day
    Vary = "Accept-Encoding"
    
[[headers]]
  # For your HTML/app shell
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # For static assets like images, CSS, JS
  for = "/assets/*"  # Adjust path based on your structure
  [headers.values]
    Cache-Control = "public, max-age=31536000" # Cache for 1 year