[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400" # Cache for 1 day
    Vary = "Accept-Encoding"

[[headers]]
  for = "/chart-jsons/*"
  [headers.values]
    Cache-Control = "public, max-age=86400" # Cache for 1 day
    Vary = "Accept-Encoding"

[[headers]]
  for = "/chart-jsons/page-content/*"
  [headers.values]
    Cache-Control = "public, max-age=86400" # Cache for 1 day
    Vary = "Accept-Encoding"
    
[[headers]]
  # For your HTML/app shell
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # For static assets like images, CSS, JS
  for = "/images/*"  # Adjust path based on your structure
  [headers.values]
    Cache-Control = "public, max-age=31536000" # Cache for 1 year

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000" # Cache for 1 year

[[headers]]
  for = "/*"
  [headers.values]
    # Add rate limiting headers
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"